### ISSUE TITLE
Application error：

### ISSUE THREAD

**Issue by opfocus** [superbridgeapp/superbridge-app#47]
![Cuplikan_layar_2024-05-11_0137093333](https://github.com/superbridgeapp/superbridge-app/assets/86885634/33b576ab-776f-4300-b1a4-3452f0d42651)
![image2222](https://github.com/superbridgeapp/superbridge-app/assets/86885634/504c0812-0a56-46ab-9ce5-88888614b9ca)
![image111](https://github.com/superbridgeapp/superbridge-app/assets/86885634/941885cc-f177-4ba4-98de-59def8fde42a)

Two users reported this error, but it disappeared when the user switched to a different wallet address. Can you help analyze the cause of the error?

**Comment by opfocus** [comment]
https://sepolia-optimism.etherscan.io/address/0xb88a1d716fa26dea1b20b2263c10ca2d7613e22f#l2withdrawaltxs
https://sepolia-optimism.etherscan.io/address/0x00c3a9893a3f8fdeb6627cbbb0cf763b36491998#l2withdrawaltxs

**Comment by AlexBHarley** [comment]
Thanks for this report.

The root cause was that our indexing process missed the Prove operation for one of the withdrawals these addresses had. We've backfilled that and will take another look to make sure no others are missed.

We also put in a fix so the entire app doesn't crash if a withdrawal is processed but we missed the prove operation.
